### ISSUE TITLE
Include git authorship metadata of recipes as yaml files in resources directory

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-build-gradle-plugin#5]
We need to update our build plugin to include a descriptor of recipe authorship in yaml format into its src/main/resources directory. 
It is difficult for a build plugin to tell which java sources are recipes and which are unrelated java source files. So for simplicity of implementation we can create a descriptor for every java source file.

Git can be queried with this information on the command line with:
`git shortlog --numbered --summary --email -- <path>`

Example output from rewrite-python. The number is the count of commits, sorted descending.
```
> git shortlog --numbered --summary --email -- src/test/java/org/openrewrite/python/tree/AssignTest.java
     3  Gary Olsen <gary@moderne.io>
     2  Jonathan Schneider <jkschneider@gmail.com>
     1  Sam Snyder <sam@moderne.io>
     1  Tim te Beek <timtebeek@gmail.com>
     1  Yeikel <email@yeikel.com>
```
It is likely more convenient and efficient to use jgit than to shell out. jgit _might_ already be part of the gradle api.

For each such java file in the main source set, we should produce an entry in `src/main/resources/META-INF/rewrite/recipe-authors.yml` that looks like:
```yaml
---
type: specs.openrewrite.org/v1beta/authors
name: org.openrewrite.python.tree.AssignTest
authors:
  - name: Gary Olsen
    email: gary@moderne.io
    commits: 3
  - name: # etc. 
  - name: 
```

Both `RewriteLanguagePlugin` and `RewriteRecipeLibraryPlugin` should register a task which produces this yaml file. The java plugin's `ProcessResources` task should be configured to copy from it so that it is guaranteed this ends up bundled in the jar.
